import { Task } from "@/generated/prisma/client";

export const MOCK_TASKS: Task[] = [
  {
    id: "1",
    title: "Fix the navigation bug",
    description: "The menu doesn't open on mobile",
    status: "TODO",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2025-12-20"),
    userId: "user_1",
  },
  {
    id: "2",
    title: "Design new landing page",
    description: "Create modern, responsive landing page with hero section",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-18"),
    userId: "user_1",
  },
  {
    id: "3",
    title: "Update documentation",
    description: "Add the new API endpoints",
    status: "DONE",
    priority: "LOW",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2025-12-25"),
    userId: "user_1",
  },
  {
    id: "4",
    title: "Refactor database schema",
    description: "Optimize schema structure and add missing indexes",
    status: "TODO",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2025-12-28"),
    userId: "user_1",
  },
  {
    id: "5",
    title: "Implement user authentication",
    description: "Login and signup with JWT",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-22"),
    userId: "user_1",
  },
  {
    id: "6",
    title: "Optimize images",
    description: "Compress hero section images",
    status: "TODO",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-05"),
    userId: "user_1",
  },
  {
    id: "7",
    title: "Add dark mode",
    description: "Implement theme toggle with light and dark themes",
    status: "TODO",
    priority: "LOW",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-15"),
    userId: "user_1",
  },
  {
    id: "8",
    title: "Set up CI pipeline",
    description: "GitHub Actions workflow",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2025-12-30"),
    userId: "user_1",
  },
  {
    id: "9",
    title: "Fix checkout validation",
    description: "Prevent empty form submission",
    status: "TODO",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-16"),
    userId: "user_1",
  },
  {
    id: "10",
    title: "Improve SEO",
    description: "Add meta tags",
    status: "DONE",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-10"),
    userId: "user_1",
  },
  {
    id: "11",
    title: "Create admin dashboard",
    description: "Build comprehensive admin panel for user management",
    status: "TODO",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-20"),
    userId: "user_1",
  },
  {
    id: "12",
    title: "Add unit tests",
    description: "Cover auth service",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-15"),
    userId: "user_1",
  },
  {
    id: "13",
    title: "Upgrade dependencies",
    description: "Update all packages to latest stable versions",
    status: "TODO",
    priority: "LOW",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-28"),
    userId: "user_1",
  },
  {
    id: "14",
    title: "Create error boundaries",
    description: "Handle app crashes gracefully",
    status: "TODO",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-20"),
    userId: "user_1",
  },
  {
    id: "15",
    title: "Implement notifications",
    description: "Toast messages for actions",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-25"),
    userId: "user_1",
  },
  {
    id: "16",
    title: "Add user profile page",
    description: "Create user settings and profile editing page",
    status: "TODO",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-25"),
    userId: "user_1",
  },
  {
    id: "17",
    title: "Integrate payment gateway",
    description: "Stripe integration",
    status: "TODO",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-05"),
    userId: "user_1",
  },
  {
    id: "18",
    title: "Improve accessibility",
    description: "ARIA labels and contrast",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-01-30"),
    userId: "user_1",
  },
  {
    id: "19",
    title: "Add loading skeletons",
    description: "Show skeleton screens during data loading",
    status: "TODO",
    priority: "LOW",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-03-01"),
    userId: "user_1",
  },
  {
    id: "20",
    title: "Fix memory leak",
    description: "Uncleared intervals",
    status: "TODO",
    priority: "HIGH",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-01"),
    userId: "user_1",
  },
  {
    id: "21",
    title: "Add search feature",
    description: "Search tasks by title",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-08"),
    userId: "user_1",
  },
  {
    id: "22",
    title: "Implement drag and drop",
    description: "Reorder tasks visually",
    status: "TODO",
    priority: "MEDIUM",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-05"),
    userId: "user_1",
  },
  {
    id: "23",
    title: "Add pagination",
    description: "Implement pagination for large task lists",
    status: "TODO",
    priority: "LOW",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-03-10"),
    userId: "user_1",
  },
  {
    id: "24",
    title: "Create export feature",
    description: "Download tasks as CSV",
    status: "DONE",
    priority: "LOW",
    createdAt: new Date(),
    updatedAt: new Date(),
    dueDate: new Date("2026-02-10"),
    userId: "user_1",
  },
];
